// Register user
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "salma@gmail.com",
    "name": "salma",
    "password": "1234"
}


###
// login user
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "salma@gmail.com",
    "password": "1234"
}

###
// logout user
POST http://localhost:3000/logout
Content-Type: application/json


###
// create category
POST http://localhost:3000/category/
Content-Type: application/json

{
    "name": "friends"
}



###
// get all categories
GET http://localhost:3000/category/
Content-Type: application/json



###
// update category
PUT http://localhost:3000/category/3
Content-Type: application/json

{
    "newName": "self"
}


###
// delete category
DELETE http://localhost:3000/category/4
Content-Type: application/json








/////////////////////////////////////////////////





###
// create todo
POST http://localhost:3000/todo/
Content-Type: application/json

{
    "description": "hello my .. todo!",
    "reminder": "2024-12-12 12:12:12",
    "categoryId": "2",
    "dueDate": "2025-12-12"
}



###
// get all todo
GET http://localhost:3000/todo/
Content-Type: application/json


###
// get all todo of category
GET http://localhost:3000/todo/22
Content-Type: application/json



###
// update todo
PUT http://localhost:3000/todo/1
Content-Type: application/json

{
    "categoryId": 24
}


###
// delete todo
DELETE http://localhost:3000/todo/1
Content-Type: application/json

